on:
  push:
  workflow_dispatch:
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v6

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: ftp.paulhibbitts.net
        username: deployftp@paulhibbitts.net
        password: ${{ secrets.DEPLOY_FTP_PASSWORD }}
        protocol: ftps-legacy
        port: 990
        timeout: 300000
        log-level: verbose
