on:
  push:
    branches: [main]
  workflow_dispatch:
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v6

      - name: 📂 Deploy via SSH
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ftp.paulhibbitts.net
          REMOTE_USER: paulhibb
          REMOTE_PORT: 22
          SOURCE: "docs/"
          TARGET: "/home/paulhibb/docsify-this.hibbittsdesign.org/"
          EXCLUDE: ".git/, .github/, .DS_Store"
